"""
Dictionary to supply information for reading and plotting validation data for size modeling
"""
from .read_size_validation_data import (read_Re_vs_Mstar_data,
                                        read_Re_vs_z_Mstar_fits,
                                        read_Re_vs_z_data)
from .plot_size_data import plot_Re_vs_Mstar_data, plot_Re_vs_z_Mstar_fits

validation_info = {'Re_vs_Mstar_data': {'missing_values': '--',
                                       'filling_values': 0.0,
                                       'reader': read_Re_vs_Mstar_data,
                                       'plotter': plot_Re_vs_Mstar_data,
                                       'xlabel': '$\\bm{\\log_{10}(M^*/M_\\odot)}$',
                                       'ylabel': '$\\bm{R_{e} (\\mathrm{kpc})}$',
                                       'lgnd_label': '$\\bm{R_e}$',
                                       'x-values': 'M*_med_{}',
                                       'y-values': ['Re_{}'],
                                       'y-errors+': ['dRe_{}+'],
                                       'y-errors-': ['dRe_{}-'],
                                       'martorano_2024': {
                                           'samples': ['All', 'Star-forming', 'Quiescent'],
                                           'colors': ['black', 'darkslateblue', 'firebrick'],
                                           'filename': 'martorano_2024_table1_Mstar_log10Re_{}.txt',
                                           'skip_header': 10,
                                           'dz': .5,
                                           'z_lo': 0.5,
                                           'z_hi': 2.5,
                                           'M*_columns': [0, 1],
                                           'M*_colnames': ['M*_lo', 'M*_hi'],
                                           'data_colnames': ['M*_med_{}', 'log10_Re_16%_{}', 'log10_Re_50%_{}', 'log10_Re_84%_{}'],
                                           'value_columns': [2],
                                           'error_columns': [3],
                                           'error_n_columns': [1],
                                           'convert_from_log': True,
                                           'convert_limits_to_errors': True,
                                           'wavelength': 1.5,
                                           'marker': 's',
                                           'short_title': 'JWST+COSMOS',
                                           'suptitle': 'Martorano et. al. 2024, JWST+COSMOS',
                                                    },
                                  },
                   'Re_vs_Mstar': {'missing_values': '--',
                                    'filling_values': 0.0,
                                    'reader': read_Re_vs_z_Mstar_fits,
                                    'plotter': plot_Re_vs_z_Mstar_fits,
                                    'y-values': ['A_{}','alpha_{}'], 
                                    'y-errors+': ['dA_{}+','dalpha_{}+'],
                                    'y-errors-': ['dA_{}-','dalpha_{}-'],
                                    'xlabels': ['$\\bm{z}$',
                                                '$\\bm{z}$'],
                                    'ylabels': ['$\\bm{A}$ (kpc)', r'$\bm\alpha$'],
                                    'titles': ['$\\bm{{A}}$: $\\bm{{R_e = A*(M^*/({} \\times 10^{{10}}M_\\odot))^{{\\alpha}}}}$',
                                               '$\\bm{{\\alpha}}$: $\\bm{{R_e = A*(M^*/({} \\times 10^{{10}}M_\\odot))^{{\\alpha}}}}$'],
                                    'x-values': ['z_med_{}'],
                                    'kawinwanichakij_2021': {
                                                 'samples': ['Quiescent', 'Star-forming'],
                                                 'colors': ['firebrick', 'royalblue'],
                                                 'filename': 'kawinwanichakij_Table5b_Re_vs_Mstar_fits.txt',
                                                 'skip_header': 4,
                                                 'M_p': 5,
                                                 'x_colnames': ['z_med'],
                                                 'x_columns': [0],
                                                 'data_colnames': ['alpha_{}', 'dalpha_{}+', 'A_{}', 'dA_{}+',
                                                                   'sigma_{}',  'dsigma_{}+'],
                                                 'copy_from_common': True,
                                                 'copy_columns': ['z_med'],
                                                 'marker': 'D', 
                                                 'wavelength': 0.5,
                                                 'short_title': 'HSC',
                                                 'suptitle': 'Kawinwanichakij et. al. 2021, HSC',
                                                },
                                   'mowla_2019': {
                                                 'samples': ['All', 'Star-forming', 'Quiescent'],
                                                 'colors': ['black', 'mediumblue', 'crimson'],
                                                 'filename': 'mowla_2019_Table2_Re_vs_Mstar_fits.txt',
                                                 'skip_header': 4,
                                                 'M_p': 7,
                                                 'x_colnames': ['z_med'],
                                                 'x_columns': [0],
                                                 'data_colnames': ['logA_{}', 'dlogA_{}+',
                                                                   'alpha_{}', 'dalpha_{}+'],
                                                 'value_columns': [0],
                                                 'error_columns': [1],
                                                 'convert_from_log': True,
                                                 'adjust_for_M_p': True,
                                                 'M_p_factor': 1.4,
                                                 'M_p_value_column': 0,
                                                 'M_p_power_column': 1,
                                                 'M_p_label': '_M_p_rescaled',
                                                 'copy_from_common': True,
                                                 'copy_columns': ['z_med'],
                                                 'marker': 'o',
                                                 'wavelength': 0.55,
                                                 'short_title': 'COSMOS-DASH',
                                                 'suptitle': 'Mowla et al. 2019, COSMOS-DASH',
                                                 },
                                   'george_2024_3000': {
                                                        'samples': ['Star-forming', 'Quiescent'],
                                                        'colors': ['mediumslateblue', 'crimson'],
                                                        'filename': 'George_2024_Table2_3000_Re_vs_Mstar_fits.txt',
                                                        'skip_header': 4,
                                                        'M_p': 5,
                                                        'x_colnames': ['zlo', 'zhi'],
                                                        'x_columns': [0, 1],
                                                        'data_colnames': ['z_med_{}', 'dz_med_{}', 'alpha_{}',
                                                                          'dalpha_{}+', 'A_{}',  'dA_{}+',
                                                                          'sigma_{}',  'dsigma_{}+',
                                                                        ],
                                                        'marker': 'X',
                                                        'wavelength': 0.3,
                                                        'short_title': 'CLAUDS+HSC',
                                                        'suptitle': 'George et. al. 2024, CLAUDS+HSC',
                                                       },
                                   'george_2024_5000': {
                                                        'samples': ['Star-forming', 'Quiescent'],
                                                        'colors': ['mediumslateblue', 'crimson'],
                                                        'filename': 'George_2024_Table2_5000_Re_vs_Mstar_fits.txt',
                                                        'skip_header': 4,
                                                        'M_p': 5,
                                                        'x_colnames': ['zlo', 'zhi'],
                                                        'x_columns': [0, 1],
                                                        'data_colnames': ['z_med_{}', 'dz_med_{}', 'alpha_{}',
                                                                          'dalpha_{}+', 'A_{}',  'dA_{}+',
                                                                          'sigma_{}',  'dsigma_{}+',
                                                                        ],
                                                        'marker': 'X',
                                                        'wavelength': 0.5,
                                                        'short_title': 'CLAUDS+HSC',
                                                        'suptitle': 'George et. al. 2024, CLAUDS+HSC',
                                                       },
                                   
                                   },
                   'Re_vs_z_data': {'missing_values': '--',
                                    'filling_values': 0.0,
                                    'reader': read_Re_vs_z_data,
                                    'plotter': plot_Re_vs_Mstar_data,
                                    'xlabel': '$\\bm{\\log_{10}(M^*/M_\\odot)}$',
                                    'ylabel': '$\\bm{R_{e}^{med} (\\mathrm{kpc})}$',
                                    'lgnd_label': '$\\bm{R_e^{med}}$',
                                    'x-values': 'M*_med',
                                    'y-values': ['Re_med_{}'],
                                    'z-values': 'z_med',
                                    'y-errors+': ['dRe_med_{}+'],
                                    'y-errors-': ['dRe_med_{}-'],
                                    'mowla_2019': {
                                                 'samples': ['All', 'Star-forming', 'Quiescent'],
                                                 'colors': ['black', 'mediumblue', 'crimson'],
                                                 'filename': 'mowla_2019_Table3_Re_vs_z_data.txt',
                                                 'skip_header': 4,
                                                 'format': 'M*_by_row',
                                                 'M*_rownames': ['M*_med_row'],
                                                 'M*_rows': [0],
                                                 'z_colnames': ['z_med_row'],
                                                 'z_columns': [0],
                                                 'data_colnames': ['Re_med_{}', 'dRe_med_{}+'],
                                                 'marker': 'o',
                                                 'wavelength': 0.55,
                                                 'short_title': 'COSMOS-DASH',
                                                 'suptitle': 'Mowla et al. 2019, COSMOS-DASH',
                                                 },
                                   'kawinwanichakij_2021': {
                                                 'samples': ['All', 'Quiescent', 'Star-forming'],
                                                 'colors': ['black', 'firebrick', 'royalblue'],
                                                 'filename': 'kawinwanichakij_Table6a_Re_median_vs_z.txt',
                                                 'skip_header': 2,
                                                 'format': 'M*_by_column',
                                                 'z_colnames': ['z_med'],
                                                 'z_columns': [3],
                                                 'M*_colnames': ['M*_lo', 'M*_hi', 'M*_med'],
                                                 'M*_columns': [0, 1, 2],
                                                 'data_colnames': ['Re_med_{}', 'dRe_med_{}+'],
                                                 'marker': 'D', 
                                                 'wavelength': 0.5,
                                                 'short_title': 'HSC',
                                                 'suptitle': 'Kawinwanichakij et. al. 2021, HSC',
                                                },
                                   },
                                 
                   'Re_vs_z': {
                               'missing_values': '--',
                               'filling_values': 0.0,
                               'reader': read_Re_vs_z_Mstar_fits,
                               'plotter': plot_Re_vs_z_Mstar_fits,
                               'x-values': ['M*med'],
                               'y-values': ['B_{}','beta_{}'], 
                               'y-errors+': ['dB_{}+','dbeta_{}+'],
                               'y-errors-': ['dB_{}-','dbeta_{}-'],
                               'xlabels': ['$\\bm{\\log_{10}(M^*/M_\\odot)}$',
                                           '$\\bm{\\log_{10}(M^*/M_\\odot)}$'],
                               'ylabels': ['$\\bm{B}$ (kpc)', r'$\bm\beta$'],
                               'titles': ['$\\bm{B}$: $\\bm{R_e = B*(1 + z)^{-\\beta}}$',
                                          '$\\bm{\\beta}$: $\\bm{R_e = B*(1 + z)^{-\\beta}}$'],
                               'xlabel': '$\\bm{z}$',
                               'ylabel': '$\\bm{\\log10(R_{e}}/\\mathrm{kpc})$',
                               'martorano_2024': {
                                   'samples': ['All', 'Star-forming', 'Quiescent'],
                                   'colors': ['black', 'darkslateblue', 'firebrick'],
                                   'filename': 'martorano_2024_table2_Re_vs_z.txt',
                                   'skip_header': 4,
                                   'x_colnames': ['M*_lo', 'M*_hi', 'M*med'],
                                   'x_columns': [0, 1, 2],
                                   'data_colnames': ['alpha_{}', 'dalpha_{}+',  'dalpha_{}-',
                                                     'beta_{}',  'dbeta_{}+', 'dbeta_{}-',
                                                ],
                                   'flip_sign': True,
                                   'flip_value_columns': 3,
                                   'convert_from_log': True,
                                   'value_columns': [0],
                                   'error_columns': [1],
                                   'error_n_columns': [2],
                                   'marker': 's',
                                   'wavelength': 1.5,
                                   'short_title': 'JWST+COSMOS',
                                   'suptitle': 'Martorano et. al. 2024, JWST+COSMOS',
                                                },
                               'george_2024_3000': {
                                   'samples': ['Star-forming', 'Quiescent'],
                                   'colors': ['mediumslateblue', 'crimson'],
                                   'filename': 'George_2024_Table3a_3000_Re_vs_z.txt',
                                   'skip_header': 5,
                                   'x_colnames': ['M*med'],
                                   'x_columns': [0],
                                   'data_colnames': ['B_{}', 'dB_{}+',
                                                     'beta_{}',  'dbeta_{}+',
                                                ],
                                   'flip_sign': True,
                                   'flip_value_columns': 2,
                                   'marker': 'X',
                                   'wavelength': 0.3,
                                   'short_title': 'CLAUDS+HSC',
                                   'suptitle': 'George et. al. 2024, CLAUDS+HSC',
                                                },
                               'george_2024_5000': {
                                   'samples': ['Star-forming', 'Quiescent'],
                                   'colors': ['mediumslateblue', 'crimson'],
                                   'filename': 'George_2024_Table3b_5000_Re_vs_z.txt',
                                   'skip_header': 5,
                                   'x_colnames': ['M*med'],
                                   'x_columns': [0],
                                   'data_colnames': ['B_{}', 'dB_{}+',
                                                     'beta_{}',  'dbeta_{}+',
                                                ],
                                   'flip_sign': True,
                                   'flip_value_columns': 2,
                                   'marker': 'P',
                                   'wavelength': 0.5,
                                   'short_title': 'CLAUDS+HSC',
                                   'suptitle': 'George et. al. 2024, CLAUDS+HSC',
                                                }, 
                               'kawinwanichakij_2021': {
                                   'samples': ['All', 'Quiescent', 'Star-forming'],
                                   'colors': ['black', 'firebrick', 'royalblue'],
                                   'filename': 'kawinwanichakij_Table6b_Re_vs_z.txt',
                                   'skip_header': 2,
                                   'x_colnames': ['M*_lo', 'M*_hi', 'M*med'],
                                   'x_columns': [0, 1, 2],
                                   'data_colnames': ['B_{}', 'dB_{}+',
                                                     'beta_{}',  'dbeta_{}+',
                                                ],
                                   'marker': 'D', 
                                   'wavelength': 0.5,
                                   'short_title': 'HSC',
                                   'suptitle': 'Kawinwanichakij et. al. 2021 -- HSC',
                                                },
                               'mowla_2019': {
                                         'samples': ['All', 'Star-forming', 'Quiescent'],
                                         'colors': ['black', 'mediumblue', 'crimson'],
                                         'filename': 'mowla_2019_Table1b_3b_Re_vs_z.txt',
                                         'skip_header': 3,
                                         'x_colnames': ['M*med'],
                                         'x_columns': [0],
                                         'data_colnames': ['B_{}', 'dB_{}+', 'beta_{}',  'dbeta_{}+'],
                                         'marker': 'o',
                                         'wavelength': 0.55,
                                         'short_title': 'COSMOS-DASH',
                                         'suptitle': 'Mowla et al. 2019, COSMOS-DASH',
                                             },
                               'vanderWel_2014': {
                                         'samples': ['Star-forming', 'Quiescent'],
                                         'colors': ['dodgerblue', 'orangered'],
                                         'filename': 'vanderWel_2014_table2_Re_vs_z.txt',
                                         'skip_header': 5,
                                         'x_colnames': ['M*med'],
                                         'x_columns': [0],
                                         'data_colnames': ['alpha_{}', 'dalpha_{}+', 'beta_{}',  'dbeta_{}+'],
                                         'marker': '^',
                                         'flip_sign': True,
                                         'flip_value_columns': 2,
                                         'convert_from_log': True,
                                         'value_columns': [0],
                                         'error_columns': [1],
                                         'wavelength': 0.5,
                                         'short_title': '3D-HST+CANDELS',
                                         'suptitle': 'van der Wel et al. 2014, 3D-HST+CANDELS',
                                             },
                              },
            }
